[package]
name = "netstat-rust"
version = "0.1.0"
authors = ["CryShana <adam.veselic@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netstat2 = "0.9.1"
sysinfo = "0.17.2"